# -*- coding: utf-8 -*-
"""pipeline gpt_bert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lAj6ewlzwyHsC7sWKrUp-u-JOY1PesV
"""


import pandas as pd

df = pd.read_csv("patient_text.csv")

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    BioGptTokenizer,
    BioGptForCausalLM
)

# ── 1. Charger BiomedBERT ────────────────────────────────
print("Chargement BiomedBERT...")
biomedbert_name = "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
biomedbert_tokenizer = AutoTokenizer.from_pretrained(biomedbert_name)
biomedbert_model = AutoModelForSequenceClassification.from_pretrained(
    biomedbert_name, num_labels=2
)
biomedbert_model.eval()
print("BiomedBERT chargé !")

# ── 2. Charger BioGPT ────────────────────────────────────
print("Chargement BioGPT...")
biogpt_tokenizer = BioGptTokenizer.from_pretrained("microsoft/biogpt")
biogpt_model = BioGptForCausalLM.from_pretrained("microsoft/biogpt")
biogpt_model.eval()
print("BioGPT chargé !")

# ── 3. Fonction classification BiomedBERT ────────────────
def classify_patient(text):
    inputs = biomedbert_tokenizer(
        text,
        max_length=256,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )
    with torch.no_grad():
        outputs = biomedbert_model(**inputs)
        pred = torch.argmax(outputs.logits, dim=1).item()
    return "ADHD" if pred == 1 else "Control"

# ── 4. Fonction génération rapport BioGPT ────────────────
def generate_report(patient_id, tbr, faa, classification):
    report_template = f"""
CLINICAL EEG REPORT
===================
Patient ID: {patient_id}
Classification: {classification}

NEUROPHYSIOLOGICAL FINDINGS:
- Frontal Theta/Beta Ratio: {tbr:.3f}
  {"ELEVATED - indicates reduced cortical activation" if tbr > 2.5 else "NORMAL"}
- Frontal Alpha Asymmetry: {faa:.3f}
  {"ABNORMAL hemispheric asymmetry detected" if abs(faa) > 100 else "NORMAL"}

CLINICAL INTERPRETATION:
"""
    inputs = biogpt_tokenizer(
        report_template + "The neurophysiological profile indicates",
        return_tensors="pt"
    )
    with torch.no_grad():
        outputs = biogpt_model.generate(
            **inputs,
            max_new_tokens=100,
            num_beams=5,
            early_stopping=True,
            no_repeat_ngram_size=3,
            repetition_penalty=2.0
        )
    return biogpt_tokenizer.decode(outputs[0], skip_special_tokens=True)

# ── 5. Pipeline complet ──────────────────────────────────
def full_pipeline(patient_id, tbr, faa, text):
    print(f"\nTraitement patient {patient_id}...")

    # BiomedBERT classifie
    classification = classify_patient(text)
    print(f"BiomedBERT → {classification}")

    # BioGPT génère le rapport
    report = generate_report(patient_id, tbr, faa, classification)
    print(report)
    return report

# ── 6. Test sur un patient Nasrabadi ────────────────────
patient = df.iloc[0]

full_pipeline(
    patient_id=patient['ID'],
    tbr=3.109,
    faa=499.060,
    text=patient['text']
)