# -*- coding: utf-8 -*-
"""test_bioGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVUM9bkVvl2YTe3PbIWRtT2hzO6C6V6W
"""

!pip install transformers torch sacremoses -q

from transformers import BioGptTokenizer, BioGptForCausalLM
import torch

# Charger le modèle et le tokenizer
model_name = "microsoft/biogpt"
tokenizer = BioGptTokenizer.from_pretrained(model_name)
model = BioGptForCausalLM.from_pretrained(model_name)

# 1. BiomedBERT classifie
classification = "ADHD"  # output de BiomedBERT
tbr = 3.109
faa = 499.060

# 2. On construit un prompt structuré et contrôlé
input_text = f"""EEG neurophysiological report for a pediatric patient.
Frontal Theta/Beta Ratio: {tbr} (elevated, normal range: 1.0-2.5)
Frontal Alpha Asymmetry: {faa}
BiomedBERT Classification: {classification}
Based on the above EEG biomarkers, the clinical findings suggest:"""

# 3. BioGPT génère le rapport
inputs = tokenizer(input_text, return_tensors="pt")

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        num_beams=5,
        early_stopping=True,
        no_repeat_ngram_size=3,
        repetition_penalty=1.5
    )

generated = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated)

def generate_clinical_report(patient_id, tbr, faa, classification):
    report = f"""
CLINICAL EEG REPORT
=
Patient ID: {patient_id}
Classification: {classification}

NEUROPHYSIOLOGICAL FINDINGS:
- Frontal Theta/Beta Ratio: {tbr:.3f}
  {"ELEVATED - indicates reduced cortical activation" if tbr > 2.5 else "NORMAL"}
- Frontal Alpha Asymmetry: {faa:.3f}
  {"ABNORMAL hemispheric asymmetry detected" if abs(faa) > 100 else "NORMAL"}

CLINICAL INTERPRETATION:
"""
    # BioGPT complète uniquement la partie interprétation
    inputs = tokenizer(
        report + "The neurophysiological profile indicates",
        return_tensors="pt"
    )
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=100,
            num_beams=5,
            early_stopping=True,
            no_repeat_ngram_size=3,
            repetition_penalty=2.0
        )
    interpretation = tokenizer.decode(outputs[0], skip_special_tokens=True)
    report += interpretation
    return report

# Test avec le patient v10p
print(generate_clinical_report("v11p", 1.2, 45.0, "Control"))